var lang = {
    'en': {
        
        'create-wallet-button': "Create Wallet",
        'import-wallet-button': "Import Wallet",
        'generateAddress': "Generate Address",
        'addressTypeLabel': "Address type:",
        'your-address': "Your Address:",
        'your-wif': "Your WIF:",
        'your-seed': "Your Seed:",
        'importantmsg': "IMPORTANT: Make sure you store your WIF key in a secure place before doing anything else",
        'alertmsg': "Address Generated Successfully",
        'block-height': "Block Height:",
        'net-hash': "Network Hashrate:",
        'circ-supply': "Circulating Supply:",
        'wifImport': "Import WIF",
        'seedImport': "Import Seed",
        'legacy': "Legacy address:",
        'alert_wif_success': "WIF Imported Successfully",
        "alert_wif_invalid": "WIF Invalid",
        'alert_seed_success': "Seed Imported Successfully",
        "alert_seed_invalid": "Seed is invalid",
        'send-to': "Send To: ",
        'amount-aok': "Amount: ",
        'sendTx': "Send Transaction",
        'showErrororSuccess': {
            'success': "Success! Transaction ID: ",
            'error': {
                'broadcast': "Broadcast Failed! Error: ",
                'funds': "Error: Not enough funds",
                'cancel': "Transaction Cancelled",
            },
        },
        'langlabel': "Language",
        'endpointlabel': "Endpoint",
        'logouttext': "Logout",
        'license': "View License",
        'balance-aok': "Balance AOK",
        'balance-token': "Balance Tokens",
        'logoutreminder': {
            'part1': "Remember to",
            'logoutlink': "Logout",
            'part2': "before exiting Chrome",
        },

        'create-wallet': "Create Wallet",
        'import-wallet': "Import Wallet",
        'your-wallet': "Your Wallet",
        'send': "Send",
        'tx-history': "History",
        'chain-info': "Chain Info",
        'settings': "Settings"
    },
    

    'fr': {
        
        'create-wallet-button': "Créer Portefeuille",
        'import-wallet-button': "Importer Portefeuille",
        'generateAddress': "Produire Adresse",
        'addressTypeLabel': "Adresse Catégorie:",
        'your-address': "Votre Adresse:",
        'your-wif': "Votre WIF:",
        'your-seed': "Votre Seed:",
        'importantmsg': "IMPORTANT: Assurez-vous conserver votre WIF clé dans un sécurise endroit avant faire quelque chose autre",
        'alertmsg': "Adresse Généré Avec succès",
        'block-height': "Bloc Hauteur:",
        'net-hash': "Réseau Taux de Hachage:",
        'circ-supply': "Circulé Réserve:",
        'wifImport': "Importer WIF",
        'seedImport': "Importer Seed",
        'legacy': "Legacy Adresse:",
        'alert_wif_success': "WIF Importé Succès",
        "alert_wif_invalid": "WIF invalide",
        'alert_seed_success': "Semences importées avec succès",
        "alert_seed_invalid": "La graine est invalide",
        'send-to': "Envoyer pour: ",
        'amount-aok': "Quantité: ",
        'sendTx': "Envoyer Transaction",
        'showErrororSuccess': {
            'success': "Succès! Transaction ID: ",
            'error': {
                'broadcast': "Diffuser Échoué! Erreur: ",
                'funds': "Erreur: Pas assez fonds",
                'cancel': "Transaction Annulé",
            },
        },
        'langlabel': "Langue",
        'endpointlabel': "Backend De Portefeuille",
        'logouttext': "Se Déconnecter",
        'license': "Voir la License",
        'balance-aok': "Équilibre AOK",
        'balance-token': "Équilibre Tokens",
        'logoutreminder': {
            'part1': "Se souvenir de",
            'logoutlink': "Se Déconnecter",
            'part2': "avant de sortir Chrome",
        },

        'create-wallet': "Créer Portefeuille",
        'import-wallet': "Importer Portefeuille",
        'your-wallet': "Votre Portefeuille",
        'send': "Envoyer",
        'tx-history': "L'histoire",
        'chain-info': "Chaîne Données",
        'settings': "Paramètres"  
           
    },

    'kr': {
        
        'create-wallet-button': "창조하다 지갑",
        'import-wallet-button': "수입 지갑",
        'generateAddress': "주소를 생성",
        'addressTypeLabel': "주소를 유형:",
        'your-address': "너의 주소를:",
        'your-wif': "너의 WIF:",
        'your-seed': "너의 Seed:",
        'importantmsg': "중대한: 하다 확실한 당신 저장되다 너의 WIF 열쇠 안에 튼튼한 곳 전에 하기 아무것도 그밖에",
        'alertmsg': "주소 생성됨 성공적으로",
        'block-height': "블록 신장:",
        'net-hash': "회로망 해시비율:",
        'circ-supply': "순환 공급품:",
        'wifImport': "수입 WIF",
        'seedImport': "수입 Seed",
        'legacy': "Legacy 주소를:",
        'alert_wif_success': "WIF 수입품 성공적으로",
        "alert_wif_invalid": "WIF 무효로 하는",
        'alert_seed_success': "종자를 성공적으로 가져왔습니다",
        "alert_seed_invalid": "시드가 잘못되었습니다",
        'send-to': "보내다 에게: ",
        'amount-aok': "양: ",
        'sendTx': "보내다 트랜잭션",
        'showErrororSuccess': {
            'success': "성공! 트랜잭션 ID: ",
            'error': {
                'broadcast': "방송 실패한! 오류: ",
                'funds': "오류: 부족한 자금",
                'cancel': "트랜잭션 취소 된",
            },
        },
        'langlabel': "언어",
        'endpointlabel': "지갑 백엔드",
        'logouttext': "로그 아웃",
        'license': "라이센스보기",
        'balance-aok': "밸런스 AOK",
        'balance-token': "밸런스 Tokens",
        'logoutreminder': {
            'part1': "기억해",
            'logoutlink': "로그 아웃",
            'part2': "종료하기 전에",
        },


        'create-wallet': "창조하다 지갑",
        'import-wallet': "수입 지갑",
        'your-wallet': "너의 지갑",
        'send': "보내다",
        'tx-history': "역사",
        'chain-info': "체인 정보",
        'settings': "설정"
    },

    'id': {
        
        'create-wallet-button': "Membuat Dompet",
        'import-wallet-button': "Impor Dompet",
        'generateAddress': "Menghasilkan Alamat",
        'addressTypeLabel': "Tipe Alamat:",
        'your-address': "Anda Alamat:",
        'your-wif': "Anda WIF:",
        'your-seed': "Anda Seed:",
        'importantmsg': "Penting: Yakinkan kamu menyimpan Anda WIF kunci di sebuah tempat yang aman sebelum perbuatan ada yang lain",
        'alertmsg': "Alamat Dihasilkan Berhasil",
        'wifImport': "Impor WIF",
        'seedImport': "Impor Seed",
        'legacy': "Legacy Alamat:",
        'alert_wif_success': "WIF yg diimpor Berhasil",
        "alert_wif_invalid": "WIF batal",
        'alert_seed_success': "Benih Berhasil Diimpor",
        "alert_seed_invalid": "Benih tidak valid",
        'block-height': "tinggi blok:",
        'net-hash': "Jaringan Tingkat-Hash:",
        'circ-supply': "Beredar Pasokan:",
        'send-to': "Kirim Untuk: ",
        'amount-aok': "Jumlahnya: ",
        'sendTx': "Kirim Transaksi",
        'showErrororSuccess': {
            'success': "Keberhasilan! Transaksi ID: ",
            'error': {
                'broadcast': "Siaran Gagal! Kesalahan: ",
                'funds': "Kesalahan: Tidak cukup dana",
                'cancel': "Transaksi Dibatalkan",
            },
        },
        'langlabel': "Bahasa",
        'endpointlabel': "Backend Dompet",
        'logouttext': "Keluar",
        'license': "Lihat Lisensi",
        'balance-aok': "Saldo AOK",
        'balance-token': "Saldo Tokens",
        'logoutreminder': {
            'part1': "Ingat untuk",
            'logoutlink': "Keluar",
            'part2': "sebelum keluar Chrome",
        },

        'create-wallet': "Membuat Dompet",
        'import-wallet': "Impor Dompet",
        'your-wallet': "Dompet Anda",
        'send': "Kirim",
        'tx-history': "Riwayat",
        'chain-info': "Data Rantai",
        'settings': "Pengaturan"
    },

    'es': {
        
        'create-wallet-button': "Billetera Crear",
        'import-wallet-button': "Billetera Importar",
        'generateAddress': "Generar la Alocución",
        'addressTypeLabel': "Tipo Dirección:",
        'your-address': "Tu alocución:",
        'your-wif': "Tu WIF:",
        'your-seed': "Tu Seed:",
        'importantmsg': "Importante: Asegurarse tú almacenar Tu WIF llave en un seguro lugar antes de hacer Algo más",
        'alertmsg': "Alocución Generado Exitosamente",
        'block-height': "Bloque Altura:",
        'net-hash': "Red Tasa de Hash:",
        'circ-supply': "Circulante Surtido:",
        'wifImport': "Importar WIF",
        'seedImport': "Importar Seed",
        'legacy': "Legacy Alocución:",
        'alert_wif_success': "WIF Importado Exitosamente",
        "alert_wif_invalid": "WIF inválido",
        'alert_seed_success': "Semilla importada con éxito",
        "alert_seed_invalid": "La semilla no es válida",
        'send-to': "Enviar a: ",
        'amount-aok': "Cantidad: ",
        'sendTx': "Enviar Transacción",
        'showErrororSuccess': {
            'success': "Éxito! Transacción ID: ",
            'error': {
                'broadcast': "Transmitir Fracasado! Error: ",
                'funds': "Error: No es Suficiente fondos",
                'cancel': "Transacción Anulado",
            },
        },
        'langlabel': "Lenguaje",
        'endpointlabel': "Backend Billetera",
        'logouttext': "Cerrar sesión",
        'license': "Ver Licencia",
        'balance-aok': "Saldo AOK",
        'balance-token': "Saldo Tokens",
        'logoutreminder': {
            'part1': "Recuerda a",
            'logoutlink': "Cerrar sesión",
            'part2': "antes de irse Chrome",
        },

        'create-wallet': "Billetera Crear",
        'import-wallet': "Billetera Importar",
        'your-wallet': "Billetera Tu",
        'send': "Enviar",
        'tx-history': "Historia",
        'chain-info': "Informacion Red",
        'settings': "El Ajuste"
    },

    'ru': {
        
        'create-wallet-button': "Кошелька Создайте",
        'import-wallet-button': "Кошелька ввозить",
        'generateAddress': "генерировать Адреса",
        'addressTypeLabel': "Адреса Тип:",
        'your-address': "Ваш Адреса:",
        'your-wif': "Ваш WIF:",
        'your-seed': "Ваш Seed:",
        'importantmsg': "Важный: Убедитесь, что вы храните ваш ключ WIF в безопасном месте, прежде чем делать что-либо еще",
        'alertmsg': "Адрес Сформирован Успешно",
        'block-height': "Высота блока:",
        'net-hash': "Хешрейт:",
        'circ-supply': "Предложение:",
        'wifImport': "Импортиране на WIF",
        'seedImport': "Импортиране на Seed",
        'legacy': "Legacy адрес:",
        'alert_wif_success': "WIF ключ успешно импортирован",
        "alert_wif_invalid": "Недействительный WIF",
        'alert_seed_success': "Семена успешно импортированы",
        "alert_seed_invalid": "Семя недействительно",
        'send-to': "послать к: ",
        'amount-aok': "сумма: ",
        'sendTx': "послать трансакция",
        'showErrororSuccess': {
            'success': "Success! трансакция ID: ",
            'error': {
                'broadcast': "передача не смогли! погрешность: ",
                'funds': "ошибка: Недостаточно фонды",
                'cancel': "трансакция отменен",
            },
        },
        'langlabel': "язык",
        'endpointlabel': "Бэкэнд Кошелька",
        'logouttext': "Выйти",
        'license': "Посмотреть лицензию",
        'balance-aok': "Баланс AOK",
        'balance-token': "Баланс Tokens",
        'logoutreminder': {
            'part1': "Помните в",
            'logoutlink': "Выйти",
            'part2': "перед выходом",
        },

        'create-wallet': "Создать кошелек",
        'import-wallet': "Импорт кошелька",
        'your-wallet': "Ваш кошелек",
        'send': "Отправить",
        'tx-history': "История",
        'chain-info': "Информация о сети",
        'settings': "Настройки"

    },

    'zh': {
        
        'create-wallet-button': "创建钱包",
        'import-wallet-button': "导入钱包",
        'generateAddress': "生成地址",
        'addressTypeLabel': "地址类型:",
        'your-address': "你的地址:",
        'your-wif': "你的WIF:",
        'your-seed': "你的 Seed:",
        'importantmsg': "重要: 在执行其他任何操作之前，请确保将WIF密钥存储在安全的地方",
        'alertmsg': "地址产生的成功",
        'block-height': "当前高度:",
        'net-hash': "全网算力:",
        'circ-supply': "流通总量:",
        'wifImport': "导入 WIF",
        'seedImport': "导入 Seed",
        'legacy': "Legacy地址:",
        'alert_wif_success': "导入WIF地址成功",
        "alert_wif_invalid": "无效的WIF",
        'alert_seed_success': "种子导入成功",
        "alert_seed_invalid": "种子无效",
        'send-to': "发送至: ",
        'amount-aok': "数量: ",
        'sendTx': "发送交易",
        'showErrororSuccess': {
            'success': "成功! 交易 ID: ",
            'error': {
                'broadcast': "广播失败! 错误: ",
                'funds': "错误: 资金不足",
                'cancel': "交易已取消",
            },
        },
        'langlabel': "语言",
        'endpointlabel': "钱包 后端",
        'logouttext': "登出",
        'license': "授权",
        'balance-aok': "余额 AOK",
        'balance-token': "余额 Tokens",
        'logoutreminder': {
            'part1': "记得 至",
            'logoutlink': "登出",
            'part2': "退出前 Chrome",
        },

        'create-wallet': "创建钱包",
        'import-wallet': "导入钱包",
        'your-wallet': "你的钱包",
        'send': "发送",
        'tx-history': "历史",
        'chain-info': "网络信息",
        'settings': "设置"
    },

    'ja': {
        
        'create-wallet-button': "作成する 財布",
        'import-wallet-button': "インポート 財布",
        'generateAddress': "生成する アドレス",
        'addressTypeLabel': "アドレス 形式:",
        'your-address': "きみの アドレス:",
        'your-wif': "きみの WIF:",
        'your-seed': "きみの Seed:",
        'importantmsg': "重要: 他の作業を行う前に、WIFキーを安全な場所に保管してください。",
        'alertmsg': "住所 生成された 成功した",
        'block-height': "ブロック 高さ:",
        'net-hash': "通信網 ハッシュレート:",
        'circ-supply': "サプライ:",
        'wifImport': "インポート WIF",
        'seedImport': "インポート Seed",
        'legacy': "Legacy 住所:",
        'alert_wif_success': "WIF 舶来 成功した",
        "alert_wif_invalid": "WIF 病弱な",
        'alert_seed_success': "シードが正常にインポートされました",
        "alert_seed_invalid": "シードが無効です",
        'send-to': "に 送る: ",
        'amount-aok': "量: ",
        'sendTx': "送る トランザクション",
        'showErrororSuccess': {
            'success': "成功! トランザクション ID: ",
            'error': {
                'broadcast': "放送 失敗! エラー: ",
                'funds': "エラー: 十分ではない 資金",
                'cancel': "トランザクション キャンセル",
            },
        },
        'langlabel': "言語",
        'endpointlabel': "財布 バックエンド",
        'logouttext': "ログアウト",
        'license': "見る ライセンス",
        'balance-aok': "残高 AOK",
        'balance-token': "残高 Tokens",
        'logoutreminder': {
            'part1': "覚えて に",
            'logoutlink': "ログアウト",
            'part2': "出る前に Chrome",
        },

        'create-wallet': "作成する 財布",
        'import-wallet': "インポート 財布",
        'your-wallet': "きみの 財布",
        'send': "送る",
        'tx-history': "歴史",
        'chain-info': "通信網 情報",
        'settings': "設定"
        
    },
}